### ISSUE TITLE
Change links to ManageIQ

### ISSUE THREAD

**Issue by chargio** [ManageIQ-Exchange/manageiq-exchange-frontend#33]
Links should be to:
ManageIQ website: http://www.manageiq.org/
ManageIQ Talk http://talk.manageiq.org/
ManageIQ in GitHub https://github.com/ManageIQ
ManageIQ-Exchange in GitHub https://github.com/ManageIQ-Exchange
CloudForms https://www.redhat.com/en/technologies/management/cloudforms
ManageIQ in Gitter https://gitter.im/manageiq

Frontend issues:
https://github.com/ManageIQ-Exchange/manageiq-exchange-frontend/issues
API issues:
https://github.com/ManageIQ-Exchange/manageiq-exchange/issues

**Comment by epastorc** [comment]
In the indexpage (footer)?
